# Site settings
baseURL = "http://daria.green/"
languageCode = "en-US"
title = "Daria Green: Functional Medicine Health Coach"
theme = "hugo-split-theme"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "© 2021 Daria Green"

[params]

  # Metadata for search engines and social sharing
  name = "Daria Green"
  description = "I am a Functional Medicine Health Coach and I am passionate about supporting you on your health journey."
  shareImage = "images/Daria_Green.jpg"
  # twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Content
  [params.content]
    name = "Daria Green"
    tagline = "Functional Medicine Health Coach"
    bio = "I am a Functional Medicine Health Coach and I am passionate about supporting you on your health journey."

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/Daria_Green.jpg"
      file_small = "images/Daria_Green_small.jpg"
      position = "33% 39%"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Forms:"

      [[params.links.list1.link]]
        text = "For new clients"
        # Link to a folder in the static directory with html redirect snippet.
        url = "new/"

#      [[params.links.list1.link]]
#        text = "Email"
#        url = "#"

#      [[params.links.list1.link]]
#        text = "Newsletter"
#        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Contact:"

      [[params.links.list2.link]]
        text = "coach@daria.green"
        url = "mailto:coach@daria.green"

#      [[params.links.list2.link]]
#        text = "Instagram"
#        url = "#"

#      [[params.links.list2.link]]
#        text = "Dribbble"
#        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Other:"

     [[params.links.list3.link]]
       text = "FMCHC Certificate"
       url = "/images/FMCHC_certificate.jpg"

     [[params.links.list3.link]]
       text = "LabGeeks Certificate"
       url = "/images/LabGeeks_certificate.png"

#      [[params.links.list3.link]]
#        text = "Link Three"
#        url = "#"
